### ISSUE TITLE
addAnimation breaks for `fade` when using empty list of meshes

### ISSUE THREAD

**Issue by floesche** [connectome-neuprint/neuVid#157]
I am not sure if your code should cover this edge case, but when the `fade` commands is provided with an empty list for the meshes, addAnimation breaks at line 502 in addAnimation:

test case:
```json
 "neurons": {
    "source": <MYSOURCE>,
    "fadeneurons": []
  }
...
["fade", {"meshes": "neurons.fadeneurons", "startingAlpha": 0.0, "endingAlpha": 1.0, "duration": 4.0, "stagger": "constant"}],
```

throws this error:

```
Error: Python: Traceback (most recent call last):
  File "/groups/reiser/home/loeschef/prj/neuVid/neuVid/addAnimation.py", line 1196, in <module>
    cmd(args)
  File "/groups/reiser/home/loeschef/prj/neuVid/neuVid/addAnimation.py", line 502, in fadeCmd
    if len(objs) >= 6:
TypeError: object of type 'NoneType' has no len()
neuVid 1.35.0

```

**Comment by hubbardp** [comment]
Thanks for the report.  I'll work on a fix now.

**Comment by floesche** [comment]
Some ideas are in #158 and #159
